# Generated by Django 3.2.3 on 2022-12-04 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='club_role',
        ),
    ]
